[[subtasks]]
group_name = "universal"
[condition]
column = "In Preparation"
[[subtasks.task]]
task = "Extension number reserved"
[[subtasks.task]]
task = "XML changes made"

[[subtasks]]
group_name = "before design review"
[subtasks.condition]
swimlane = "Design Review phase"
column = "In Preparation"
[[subtasks.task]]
task = "Initial ADOC stubbed out"
migration_prefix = "ADOC written"

[[subtasks]]
group_name = "before spec review"
[subtasks.condition]
swimlane = "Spec Review phase"
column = "In Preparation"
[[subtasks.task]]
task = "Changelog fragments written"
[[subtasks.task]]
task = "Full ADOC spec written"
migration_prefix = "ADOC written"
[[subtasks.task]]
task = "Champion reviewed generated HTML output (`./makeAllExts html`)"
migration_prefix = "Champion reviewed generated HTML output"
[[subtasks.task]]
task = "Champion reviewed generated header (`./makeAllExts header`)"
migration_prefix = "Champion reviewed generated header"
[[subtasks.task]]
task = "Champion reviewed generated ref/man pages (`./makeAllExts manhtmlpages`)"
migration_prefix = "Champion reviewed generated ref/man pages"
[[subtasks.task]]
task = "Champion performed self-review using the [Extension Review](https://gitlab.khronos.org/openxr/openxr/-/wikis/extension-review) checklist"
migration_prefix = "Champion performed self-review"

[[subtasks]]
group_name = "before publication"
[subtasks.condition]
swimlane = "Spec Review phase"
column = "In Preparation"
# exclude_category = "Not Subject to IPR Policy"
exclude_categories = true
[[subtasks.task]]
task = "CTS tests written"
migration_prefix = "CTS tests written"


[[subtasks]]
group_name = "before publication"
[subtasks.condition]
swimlane = "Spec Review phase"
column = "In Preparation"
category = "Not Subject to IPR Policy"
[[subtasks.task]]
task = "CTS tests written (optional)"
migration_prefix = "CTS tests written"

[[subtasks]]
group_name = "ratification submission"
[subtasks.condition]
swimlane = "Spec Review phase"
column = "Pending Approvals And Merge"
# exclude_category = "Not Subject to IPR Policy"
exclude_categories = true
[[subtasks.task]]
task = "WG vote to submit passed with a 3/4 majority"
[[subtasks.task]]
task = "Submission package available for Promoter review"

[[subtasks]]
group_name = "ratification"
[subtasks.condition]
swimlane = "Spec Review phase"
column = "Pending Approvals And Merge"
# exclude_category = "Not Subject to IPR Policy"
exclude_categories = true
[[subtasks.task]]
task = "OpenXR specification ratified by Promoters"
[[subtasks.task]]
task = "Loader support (if required) ready for release"
